default_stages: [pre-commit, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        exclude: |
          (?x)^(
              gitleaks.toml|
              path/to/file2.py
          )$
      - id: check-json
      - id: check-toml
      - id: check-xml
      # - id: detect-aws-credentials
      - id: detect-private-key
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
        name: gitleaks
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.3
    hooks:
      - id: djlint-jinja
        name: djlint-jinja
      - id: djlint-golang
        name: djlint-golang
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        name: gitlint
  - repo: local
    hooks:
      - id: trufflehog
        name: trufflehog
        description: Detect secrets
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --only-verified --fail --no-update'
        language: system
        stages: ["pre-commit", "pre-push"]
